### ISSUE TITLE
Webpage title overlaps with page's content

### ISSUE THREAD

**Issue by byxor** [Deniall/krayatedocs#1]
This is a small bug (presumably CSS).

![Image showing the bug](http://i.imgur.com/JIu7H0T.png)

**Comment by byxor** [comment]
Update: The bug is caused by expanding the width of the window. I've tested it on chrome/iexplorer and it looks fine when the width is below 1000ish pixels.

**Comment by Deniall** [comment]
Fixed issue by putting page content into a section. Thanks!

**Comment by byxor** [comment]
Great! I've deleted my fork. :)
